### ISSUE TITLE
Include solana linter

### ISSUE THREAD

**Issue by thegreat-vanderlinde** [vyper-protocol/vyper-core#83]
We have to include solana linter from https://github.com/crytic/solana-lints

In root `Cargo.toml`:
```toml
[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/crytic/solana-lints", pattern = "lints/*" },
]
```
